# Generated by Django 5.0.3 on 2024-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0002_user_avatar_url_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('login', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
