# Generated by Django 5.0.3 on 2024-03-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0004_repos_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repos',
            name='users',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
