# Generated by Django 5.0.3 on 2024-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0008_alter_repos_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repos',
            name='users',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
