# Generated by Django 5.0.3 on 2024-03-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0009_alter_repos_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repos',
            name='users',
        ),
        migrations.AddField(
            model_name='repos',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
