# Generated by Django 5.0.3 on 2024-03-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0011_repos_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repos',
            name='data',
        ),
        migrations.AlterField(
            model_name='repos',
            name='users',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
