# Generated by Django 5.0.3 on 2024-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0013_alter_repos_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('html_url', models.CharField(blank=True, max_length=100)),
                ('login', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='repos',
            old_name='users',
            new_name='contributers',
        ),
        migrations.RemoveField(
            model_name='repos',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='repos',
            name='pull_requests',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='users',
            name='html_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
