# Generated by Django 5.0.3 on 2024-03-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0014_pulls_rename_users_repos_contributers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repos',
            name='login',
        ),
    ]
