# Generated by Django 5.0.3 on 2024-05-17 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0017_rename_user_test_commit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('body', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='comments',
        ),
        migrations.AddField(
            model_name='commit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
