# Generated by Django 5.0.3 on 2024-05-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0018_comment_remove_pullrequest_comments_commit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='body',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='semantic_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='commit',
            name='semantic_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='repos',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
