# Generated by Django 5.0.3 on 2024-05-27 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0019_remove_commit_body_remove_commit_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repos',
            name='contributers',
        ),
        migrations.RemoveField(
            model_name='repos',
            name='pull_requests',
        ),
        migrations.AddField(
            model_name='comment',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api_integration.pullrequest'),
        ),
        migrations.AddField(
            model_name='commit',
            name='puul_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='api_integration.pullrequest'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='api_integration.repos'),
        ),
        migrations.AddField(
            model_name='repos',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
