# Generated by Django 5.0.3 on 2024-05-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0020_remove_repos_contributers_remove_repos_pull_requests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='puul_request',
            new_name='pull_request',
        ),
    ]
