# Generated by Django 5.0.3 on 2024-05-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0023_alter_pullrequest_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
