# Generated by Django 5.0.3 on 2024-05-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0024_alter_pullrequest_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repos',
            new_name='Repository',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api_integration.pullrequest'),
        ),
    ]
