# Generated by Django 5.0.2 on 2024-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0026_user_comments_user_commits_user_pull_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='commits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='pull_requests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='repositories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
