# Generated by Django 5.0.2 on 2024-05-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0027_alter_user_comments_alter_user_commits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='commits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='pull_requests_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
