# Generated by Django 5.0.3 on 2024-06-05 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0028_repository_commits_repository_pull_requests_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='commit_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='closed_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
