# Generated by Django 5.0.2 on 2024-06-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0029_comment_comment_type_comment_commit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
