# Generated by Django 5.0.2 on 2024-06-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0030_repository_comments_repository_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='comments',
            new_name='comments_list',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='commits',
            new_name='commits_list',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='users',
            new_name='users_list',
        ),
    ]
