# Generated by Django 5.0.2 on 2024-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0032_authenticateduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduser',
            name='test',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
