# Generated by Django 5.0.2 on 2024-06-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0035_delete_superuser_remove_authenticateduser_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthenticatedUser',
        ),
    ]
