# Generated by Django 5.0.2 on 2024-06-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0030_alter_comment_date_alter_commit_date_and_more'),
        ('api_integration', '0036_delete_authenticateduser'),
    ]

    operations = [
    ]
