# Generated by Django 5.0.2 on 2024-06-17 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0037_merge_20240616_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='average_semantic_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='closed_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
